name: Build and Deploy Spring Boot to Google Cloud

on:
  push:
    branches:
      - main  # Cấu hình để chạy khi có push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx (để build image với multi-platform nếu cần)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/ecom-442616/spring-boot-app:latest .

      # 4. Login to Google Cloud Container Registry (GCR)
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Lưu thông tin tài khoản Google Cloud dưới dạng secrets

      # 5. Push Docker Image lên Google Container Registry (GCR)
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/ecom-442616/spring-boot-app:latest

      # 6. SSH vào Google Cloud instance và deploy ứng dụng
      - name: SSH into Google Cloud Instance and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.GCP_INSTANCE_IP }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}  # Lưu khóa SSH dưới dạng secrets
          script: |
            # Dừng container cũ nếu có
            docker ps -q --filter "name=spring-boot-app" | xargs -r docker stop
            docker ps -aq --filter "name=spring-boot-app" | xargs -r docker rm
            # Pull image mới và chạy container mới
            docker pull gcr.io/ecom-442616/spring-boot-app:latest
            docker run -d -p 8888:8888 --name spring-boot-app gcr.io/ecom-442616/spring-boot-app:latest
